accounts:
  - name: alice
    coins: ["20000ONX", "100ORN"]
  - name: bob
    coins: ["10000ONX", "100ORN"]
validator:
  name: alice
  staked: "10000ONX"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5ONX", "10ORN"]
genesis:
  app_state:
    oracle:
      params:
        claim_params:
          PaymentMadeClaim: # This is our oracle 'type'
            vote_period: 3 # Voting round duration in blocks
            claim_type: 'AtomClaim' # Oracle type again
            prevote: true # Require commit-reveal type voting to avoid free-rider problem
            vote_threshold: '0.5' # Validator power threshold required to reach consensus
